[package]
name = "network-tools"
version = "0.1.0"
authors = ["Matthew Wood <mat@thepacketgeek.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
etherparse = "0.9.0"
pnet = "0.27"
structopt = "0.3"
ipnetwork = "0.17"
ip_network_table-deps-treebitmap = "0.5.0"